version: '3.8'

services:
  nginx:
    image: nginx:1.29.5-alpine
    container_name: kzn-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: kzn-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres-db:
      image: postgres:15-alpine
      container_name: nexus-postgres
      restart: always
      environment:
        POSTGRES_USER: nexus
        POSTGRES_DB: nexus
        POSTGRES_PASSWORD: supertajnehaslo123
      ports:
        - "5423:5432"
      volumes:
        - nexus_pg_data:/var/lib/postgresql/data

volumes:
  nexus_pg_data: